{% set name = "quaternion" %}
{% set pypiname = "numpy-quaternion" %}
{% set version = "2021.3.11.10.32.22" %}
{% set sha256 = "49319fb9243e577b424166c1b1e68a13ff2a649315b1a9ceae6a2ad74dc4cf4c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypiname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: package_version={{ version }} python -m pip install --no-deps --ignore-installed .  # [not win]
  script: set "package_version={{ version }}" && python -m pip install --no-deps --ignore-installed .  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - quaternion

about:
  home: https://github.com/moble/quaternion
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Add built-in support for quaternions to numpy
  description: |
    This package creates a quaternion type in python, and further enables
    numpy to create and manipulate arrays of quaternions.  The usual
    algebraic operations (addition and multiplication) are available,
    along with numerous properties like norm and various types of distance
    measures between two quaternions.  There are also additional functions
    like "squad" and "slerp" interpolation, and conversions to and from
    axis-angle, matrix, and Euler-angle representations of rotations.  The
    core of the code is written in C for speed.
  doc_url: https://github.com/moble/quaternion#usage
  dev_url: https://github.com/moble/quaternion

extra:
  recipe-maintainers:
    - moble
